package com.dev.payments.framework.model;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.CsvSource;

import java.time.Instant;

import static org.assertj.core.api.Assertions.assertThat;

@DisplayName("OutboxEntry")
class OutboxEntryTest {

    // -------------------------------------------------------------------------
    // Builder defaults
    // -------------------------------------------------------------------------

    @Nested
    @DisplayName("given a minimal builder invocation")
    class GivenMinimalBuilder {

        @Test
        @DisplayName("when build is called, then id is auto-generated as a UUID")
        void whenBuild_thenIdIsAutoGeneratedUuid() {
            // When
            OutboxEntry entry = minimalEntry();

            // Then
            assertThat(entry.getId())
                .as("id should be auto-generated")
                .isNotNull()
                .hasSize(36); // standard UUID length
        }

        @Test
        @DisplayName("when build is called, then status defaults to PENDING")
        void whenBuild_thenStatusDefaultsToPending() {
            assertThat(minimalEntry().getStatus())
                .isEqualTo(OutboxEntry.OutboxStatus.PENDING);
        }

        @Test
        @DisplayName("when build is called, then createdAt is set automatically")
        void whenBuild_thenCreatedAtIsSet() {
            Instant before = Instant.now();
            OutboxEntry entry = minimalEntry();
            Instant after = Instant.now();

            assertThat(entry.getCreatedAt())
                .isAfterOrEqualTo(before)
                .isBeforeOrEqualTo(after);
        }

        @Test
        @DisplayName("when build is called, then httpMethod defaults to POST")
        void whenBuild_thenHttpMethodDefaultsToPost() {
            assertThat(minimalEntry().getHttpMethod()).isEqualTo("POST");
        }
    }

    // -------------------------------------------------------------------------
    // isReadyForProcessing
    // -------------------------------------------------------------------------

    @Nested
    @DisplayName("given a PENDING entry")
    class GivenPendingEntry {

        @Test
        @DisplayName("when isReadyForProcessing is called, then returns true")
        void whenIsReadyForProcessing_thenReturnsTrue() {
            OutboxEntry entry = entryWithStatus(OutboxEntry.OutboxStatus.PENDING);
            assertThat(entry.isReadyForProcessing()).isTrue();
        }
    }

    @Nested
    @DisplayName("given a RETRY_PENDING entry with a past nextRetryAt")
    class GivenRetryPendingEntryDue {

        @Test
        @DisplayName("when isReadyForProcessing is called, then returns true")
        void whenIsReadyForProcessing_thenReturnsTrue() {
            OutboxEntry entry = OutboxEntry.builder()
                .idempotencyKey("txn-001")
                .destination("LEDGER")
                .payload("{}")
                .status(OutboxEntry.OutboxStatus.RETRY_PENDING)
                .nextRetryAt(Instant.now().minusSeconds(1))
                .build();

            assertThat(entry.isReadyForProcessing()).isTrue();
        }
    }

    @Nested
    @DisplayName("given a RETRY_PENDING entry with a future nextRetryAt")
    class GivenRetryPendingEntryNotYetDue {

        @Test
        @DisplayName("when isReadyForProcessing is called, then returns false")
        void whenIsReadyForProcessing_thenReturnsFalse() {
            OutboxEntry entry = OutboxEntry.builder()
                .idempotencyKey("txn-001")
                .destination("LEDGER")
                .payload("{}")
                .status(OutboxEntry.OutboxStatus.RETRY_PENDING)
                .nextRetryAt(Instant.now().plusSeconds(60))
                .build();

            assertThat(entry.isReadyForProcessing()).isFalse();
        }
    }

    @Nested
    @DisplayName("given a DELIVERED entry")
    class GivenDeliveredEntry {

        @Test
        @DisplayName("when isReadyForProcessing is called, then returns false")
        void whenIsReadyForProcessing_thenReturnsFalse() {
            assertThat(entryWithStatus(OutboxEntry.OutboxStatus.DELIVERED).isReadyForProcessing()).isFalse();
        }
    }

    @Nested
    @DisplayName("given a permanently FAILED entry")
    class GivenPermanentlyFailedEntry {

        @Test
        @DisplayName("when isReadyForProcessing is called, then returns false")
        void whenIsReadyForProcessing_thenReturnsFalse() {
            assertThat(entryWithStatus(OutboxEntry.OutboxStatus.FAILED).isReadyForProcessing()).isFalse();
        }
    }

    // -------------------------------------------------------------------------
    // isLocked
    // -------------------------------------------------------------------------

    @Nested
    @DisplayName("given an entry locked by a node with a future expiry")
    class GivenLockedEntry {

        @Test
        @DisplayName("when isLocked is called, then returns true")
        void whenIsLocked_thenReturnsTrue() {
            OutboxEntry entry = OutboxEntry.builder()
                .idempotencyKey("txn-001")
                .destination("LEDGER")
                .payload("{}")
                .lockedBy("node-A")
                .lockExpiresAt(Instant.now().plusSeconds(60))
                .build();

            assertThat(entry.isLocked()).isTrue();
        }
    }

    @Nested
    @DisplayName("given an entry with an expired lock")
    class GivenExpiredLock {

        @Test
        @DisplayName("when isLocked is called, then returns false")
        void whenIsLocked_thenReturnsFalse() {
            OutboxEntry entry = OutboxEntry.builder()
                .idempotencyKey("txn-001")
                .destination("LEDGER")
                .payload("{}")
                .lockedBy("node-A")
                .lockExpiresAt(Instant.now().minusSeconds(1))
                .build();

            assertThat(entry.isLocked()).isFalse();
        }
    }

    @Nested
    @DisplayName("given an entry with no lock")
    class GivenUnlockedEntry {

        @Test
        @DisplayName("when isLocked is called, then returns false")
        void whenIsLocked_thenReturnsFalse() {
            assertThat(minimalEntry().isLocked()).isFalse();
        }
    }

    // -------------------------------------------------------------------------
    // calculateNextRetry — exponential backoff formula
    // -------------------------------------------------------------------------

    @Nested
    @DisplayName("given exponential backoff calculation")
    class GivenBackoffCalculation {

        @ParameterizedTest(name = "retryCount={0}, baseDelay={1}s, maxDelay={2}s → expectedDelay={3}s")
        @CsvSource({
            "0, 30, 3600, 30",    // 30 × 2^0 = 30
            "1, 30, 3600, 60",    // 30 × 2^1 = 60
            "2, 30, 3600, 120",   // 30 × 2^2 = 120
            "3, 30, 3600, 240",   // 30 × 2^3 = 240
            "4, 30, 3600, 480",   // 30 × 2^4 = 480
            "7, 30, 3600, 3600",  // 30 × 2^7 = 3840, capped at 3600
        })
        @DisplayName("when calculateNextRetry is called, then next retry follows min(base × 2^n, max) formula")
        void whenCalculateNextRetry_thenFollowsExponentialBackoffFormula(
                int retryCount, int baseDelay, int maxDelay, int expectedDelaySecs) {

            // Given
            OutboxEntry entry = OutboxEntry.builder()
                .idempotencyKey("txn-001")
                .destination("LEDGER")
                .payload("{}")
                .retryCount(retryCount)
                .build();

            Instant before = Instant.now();

            // When
            Instant nextRetry = entry.calculateNextRetry(baseDelay, maxDelay);

            // Then
            Instant expectedNextRetry = before.plusSeconds(expectedDelaySecs);
            // Allow 2-second window for test execution time
            assertThat(nextRetry)
                .as("nextRetryAt should be approximately now + %ds", expectedDelaySecs)
                .isAfterOrEqualTo(expectedNextRetry.minusSeconds(2))
                .isBeforeOrEqualTo(expectedNextRetry.plusSeconds(2));
        }
    }

    // -------------------------------------------------------------------------
    // markDelivered
    // -------------------------------------------------------------------------

    @Nested
    @DisplayName("given a PENDING entry")
    class GivenPendingEntryForDelivery {

        @Test
        @DisplayName("when markDelivered is called, then status is DELIVERED and deliveredAt is set")
        void whenMarkDelivered_thenStatusIsDeliveredAndDeliveredAtIsSet() {
            // Given
            OutboxEntry entry = minimalEntry();
            Instant before = Instant.now();

            // When
            entry.markDelivered();

            // Then
            assertThat(entry.getStatus()).isEqualTo(OutboxEntry.OutboxStatus.DELIVERED);
            assertThat(entry.getDeliveredAt())
                .isNotNull()
                .isAfterOrEqualTo(before);
        }
    }

    // -------------------------------------------------------------------------
    // Helpers
    // -------------------------------------------------------------------------

    private OutboxEntry minimalEntry() {
        return OutboxEntry.builder()
            .idempotencyKey("txn-001")
            .destination("LEDGER")
            .payload("{\"amount\":100}")
            .build();
    }

    private OutboxEntry entryWithStatus(OutboxEntry.OutboxStatus status) {
        return OutboxEntry.builder()
            .idempotencyKey("txn-001")
            .destination("LEDGER")
            .payload("{}")
            .status(status)
            .build();
    }
}
